stockpilot:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: stockpilot
      password: stockpilot_dev
      port: 5433
      dbname: stockpilot
      schema: analytics
      threads: 4
      keepalives_idle: 0
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
  target: dev